package interfaces;

import Helpers.Verificaciones;
import Inicio.Inicio_App;
import clases.Administrador;
import clases.DataBase;
import clases.Evento;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Julián HC
 */
public class Actualizar_Evento extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_App
     */
    public Actualizar_Evento() {
        initComponents();
        this.tituloo.setText(titulo);
        this.horaa.setText(hora);
        this.date.setText(fecha);
        this.voluntarios.setText(cantidad_Voluntarios);
        this.correoo.setText(lugar);
        this.lugarr.setText(correo_Administrador);
        this.arboles.setText(cantidad_Arboles); 
    }
    static String titulo = "";
    static  String hora = "";
    static String fecha = "";
    static String cantidad_Voluntarios = "";
    static String correo_Administrador = "";
    static String lugar = "";
    static String cantidad_Arboles = "";
    static String ID = ""; 

    static public void setData(String t, String h, String f, String cV,
                        String cA, String l, String cAr, String ide){
        titulo = t;
        hora = h;
        fecha = f;
        cantidad_Voluntarios = cV;
        correo_Administrador = cA;
        lugar = l;
        cantidad_Arboles = cAr;
        ID = ide;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        tituloo = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        horaa = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        arboles = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        voluntarios = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        correoo = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        lugarr = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jPanel3.setBackground(new java.awt.Color(78, 184, 222));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Julián HC\\Documents\\NetBeansProjects\\INTERFACES_GRAFICAS\\src\\main\\java\\com\\mycompany\\interfaces_graficas\\img\\favicon.png")); // NOI18N
        jLabel5.setText("GREEN WORLD");

        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(627, 627, 627))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ACTUALIZAR UNA ENTRADA DE EVENTO.");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel40.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("CANTIDAD DE VOLUNTARIOS");
        background.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 20));

        tituloo.setBackground(new java.awt.Color(255, 255, 255));
        tituloo.setForeground(new java.awt.Color(153, 153, 255));
        tituloo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tituloo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulooActionPerformed(evt);
            }
        });
        background.add(tituloo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 370, 40));

        jLabel45.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("LUGAR");
        background.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 20));

        horaa.setBackground(new java.awt.Color(255, 255, 255));
        horaa.setForeground(new java.awt.Color(153, 153, 255));
        horaa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        horaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaaActionPerformed(evt);
            }
        });
        background.add(horaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 370, 40));

        jLabel46.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("ÁRBOLES TOTALES");
        background.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, 20));

        arboles.setBackground(new java.awt.Color(255, 255, 255));
        arboles.setForeground(new java.awt.Color(153, 153, 255));
        arboles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        arboles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arbolesActionPerformed(evt);
            }
        });
        background.add(arboles, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 370, 40));

        jLabel38.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("TÍTULO");
        background.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        voluntarios.setBackground(new java.awt.Color(255, 255, 255));
        voluntarios.setForeground(new java.awt.Color(153, 153, 255));
        voluntarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        voluntarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voluntariosActionPerformed(evt);
            }
        });
        background.add(voluntarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 370, 40));

        jLabel44.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("FECHA");
        background.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 20));

        correoo.setBackground(new java.awt.Color(255, 255, 255));
        correoo.setForeground(new java.awt.Color(153, 153, 255));
        correoo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        correoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correooActionPerformed(evt);
            }
        });
        background.add(correoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 370, 40));

        jLabel47.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("CORREO ADMINISTRADOR");
        background.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 20));

        lugarr.setBackground(new java.awt.Color(255, 255, 255));
        lugarr.setForeground(new java.awt.Color(153, 153, 255));
        lugarr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lugarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarrActionPerformed(evt);
            }
        });
        background.add(lugarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 370, 40));

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setForeground(new java.awt.Color(153, 153, 255));
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        background.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 370, 40));

        jLabel48.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("HORA");
        background.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, 20));

        jButton4.setBackground(new java.awt.Color(255, 232, 82));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("ACTUALIZAR EVENTO");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        background.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 370, 50));

        jButton3.setBackground(new java.awt.Color(204, 0, 204));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("VOLVER");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        background.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arbolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arbolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arbolesActionPerformed

    private void voluntariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voluntariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voluntariosActionPerformed

    private void titulooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulooActionPerformed

    private void horaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaaActionPerformed

    private void correooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correooActionPerformed

    private void lugarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarrActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        Dashboard_Administrador ventana = new Dashboard_Administrador();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String titulo = this.tituloo.getText();
        String hora = this.horaa.getText();
        String fecha = this.date.getText();
        String voluntarios = this.voluntarios.getText();
        String correo = this.correoo.getText();
        String lugar = this.lugarr.getText();
        String arboles = this.arboles.getText();
        this.ID = ID;
        int resultado = 0;
        
        Evento evento = new Evento(titulo,correo, lugar,arboles, fecha,voluntarios,hora);
        evento.setId(ID);
        
        boolean verificar = Verificaciones.espaciosBlanco(titulo,correo,lugar, arboles, fecha,voluntarios,hora);
        Verificaciones.verificarCorreo(correo);
        
        try {
            System.out.println(verificar);
            //---INSERTAR EN TABLA DE BASE DE DATOS---
            if(!verificar) resultado = evento.actualizar();
        } catch (SQLException ex) {
            Logger.getLogger(Crear_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arboles;
    private javax.swing.JPanel background;
    private javax.swing.JTextField correoo;
    private javax.swing.JTextField date;
    private javax.swing.JTextField horaa;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lugarr;
    private javax.swing.JTextField tituloo;
    private javax.swing.JTextField voluntarios;
    // End of variables declaration//GEN-END:variables
}
